# --- Advent of code 2020: Day 23 ---

# (File automatically generated by aocTool, developed by B0lu, 2020.)

cups = [int(e) for e in open("input.txt").read().strip()]
current = cups[0]

for i in range(100):
	shift = cups[cups.index(current) + 1:cups.index(current) + 1 + 3]
	if len(shift) < 3:
		shift.extend(cups[:3 - len(shift)])

	for cup in shift:
		cups.remove(cup)

	dest = current - 1
	if dest < min(cups):
		dest = max(cups)
	while dest not in cups:
		dest -= 1
		if dest < min(cups):
			dest = max(cups)


	dest = cups.index(dest) + 1
	for cup in shift[::-1]:
		cups.insert(dest, cup)

	#print(cups, shift, dest, current)
	current = cups[(cups.index(current) + 1) % len(cups)]

print(f"Labels of the cups after 1: {str(cups[cups.index(1) + 1:])[1:-1].replace(', ', '') + str(cups[:cups.index(1)])[1:-1].replace(', ', '')}")
assert int(str(cups[cups.index(1) + 1:])[1:-1].replace(", ", "") + str(cups[:cups.index(1)])[1:-1].replace(", ", "")) == 52864379
