# --- Advent of code 2020: Day 23 ---

# (File automatically generated by aocTool, developed by B0lu, 2020.)

cups = [int(e) for e in open("input.txt").read().strip()]
current = cups[0]

indices = {cups[i]: cups[(i + 1) % len(cups)] for i in range(len(cups))}

indices[cups[-1]] = max(cups) + 1
for i in range(max(cups) + 1, 1000000 + 1):
	indices[i] = i + 1
indices[1000000] = cups[0]
MAX = 1000000
LEN = MAX + 1
#MAX = max(cups)

for i in range(10*MAX):
	pick = []
	c = current
	for j in range(3):
		pick.append(indices[c])
		c = pick[-1]

	indices[current] = indices[c]

	dest = current - 1
	if dest < 1:
		dest = MAX
	while dest in pick:
		dest -= 1
		if dest < 1:
			dest = MAX

	c = indices[current]
	n = 1

	indices[pick[2]] = indices[dest]
	indices[dest] = pick[0]

	current = indices[current]

dest1 = indices[1]
dest2 = indices[dest1]

print(f"Cups with your stars: {dest1, dest2}")
print(f"Product of the labels of the cups with your stars: {dest1 * dest2}")
assert dest1 * dest2 == 11591415792
