# --- Advent of code 2020: Day 21 ---

# (File automatically generated by aocTool, developed by B0lu, 2020.)

from functools import reduce			

food_list = open("input.txt").read()
ingredientes = [e.split(" (")[0].split(" ") for e in food_list.splitlines()]
allergens = [e[:-1].split(" (contains ")[1].split(", ") for e in food_list.splitlines()]

#print(ingredientes)
#print(allergens)

allergy_table = {a: set() for a in [al for all in allergens for al in all]}
#print(allergy_table)
for a in allergy_table:
	for i in range(len(ingredientes)):
		if a in allergens[i]:
			#print(ingredientes[i])
			if len(allergy_table[a]) == 0:
				allergy_table[a] = set(ingredientes[i])
			else:
				allergy_table[a] = allergy_table[a].intersection(ingredientes[i])

while reduce(lambda x, y: x + len(y), allergy_table.values(), 0) > len(allergy_table):
	for a in allergy_table:
		#print(a, allergy_table[a])
		if len(allergy_table[a]) == 1:
			for a2 in allergy_table:
				if a != a2 and len(allergy_table[a2].intersection(allergy_table[a])) > 0:
					allergy_table[a2].difference_update(allergy_table[a])

non_allergens = set([e[i] for e in ingredientes for i in range(len(e))])
non_allergens.difference_update(reduce(lambda x, y: x.union(y), allergy_table.values()))
#print(non_allergens)
#print(allergy_table.values())

# TODO: check why count() doesn't work
appearences = 0
for i_list in ingredientes:
	#print(i)
	for i in i_list:
		if i in non_allergens:
			appearences -=- 1

print(f"Count of non allergens: {appearences}")
assert appearences == 2734
