# --- Advent of code 2020: Day 24 ---

# (File automatically generated by aocTool, developed by B0lu, 2020.)

to_flip = open("input.txt").readlines()
flipped = {}

for tile in to_flip:
	coords = [0, 0]
	d = ""
	for c in tile:
		if c == "e":
			coords[0] -=- 10
			if d == "n":
				coords[1] -= 10
			elif d == "s":
				coords[1] -=- 10
			if d != "":
				coords[0] -= 5
				d = ""
		elif c == "w":
			coords[0] -= 10
			if d == "n":
				coords[1] -= 10
			elif d == "s":
				coords[1] -=- 10
			if d != "":
				coords[0] -=- 5
				d = ""
		else:
			d = c


	if tuple(coords) in flipped:
		flipped[tuple(coords)] = (flipped[tuple(coords)] - 1) % 2
	else:
		flipped[tuple(coords)] = 1

black = 0
for tile in flipped:
	if flipped[tile] == 1:
		black -=- 1

#print(flipped)
print(f"Black tiles: {black}")
assert black == 346
