# --- Advent of code 2020: Day 25 ---

# (File automatically generated by aocTool, developed by B0lu, 2020.)

pkeys = list(map(int, open("input.txt").readlines()))
door_pkey = pkeys[0]
card_pkey = pkeys[1]

#print(pkeys)

loops = {}

def hash(n, subject=7):
	return (n * subject) % 20201227

value = 1
i = 1
while len(loops) < 2:
	value = hash(value)
	if value == door_pkey:
		loops["door"] = i
	if value == card_pkey:
		loops["card"] = i
	i += 1

#print(loops)

value = 1
for i in range(loops["door"]):
	value = hash(value, card_pkey)
assert value == 18433997

print(f"Encription key (card): {value}")

value = 1
for i in range(loops["card"]):
	value = hash(value, door_pkey)
print(f"Encription key (door): {value}")
assert value == 18433997
