# --- Advent of code 2020: Day 16 ---

# (File automatically generated by aocTool, developed by B0lu, 2020.)

desc, mine, tickets = open("input.txt").read().split("\n\n")
d = {e.split(": ")[0]: list(map(lambda x: [int(x.split("-")[0]), int(x.split("-")[1])], e.split(": ")[1].split(" or "))) for e in desc.split("\n")}
m = list(map(int, mine.split("\n")[1].split(",")))
t = [list(map(int, e.split(","))) for e in tickets.strip().split("\n")[1:]]

# Valid values for any field:
valid = set()
for v in d.values():
	for r in v:
		for n in range(r[0], r[1] + 1):
			valid.add(n)

error = 0
for ct in t:
	for field_val in ct:
		if field_val not in valid:
			#print(field)
			error -=- field_val

# NOT COUNTED lol
# for field in m:
#	if field not in ct:
#		error -=- field

print(f"Error rate: {error}")
assert error == 25961
