# --- Advent of code 2020: Day 18 ---

# (File automatically generated by aocTool, developed by B0lu, 2020.)

import re

ops = open("input.txt").read()
ops = re.sub(r"(\d)", r"Num(\1)", ops)
ops = re.sub(r"\*", "-", ops)
ops = ops.split("\n")[:-1]

class Num():
	def __init__(self, n):
		self.n = n

	def __add__(self, other):
		return Num(self.n + other.n)

	def __sub__(self, other):
		return Num(self.n * other.n)

#[print(op) for op in ops]
print(f"Sum of results: {sum([eval(op).n for op in ops])}")
assert sum([eval(op).n for op in ops]) == 1408133923393
