# --- Advent of code 2020: Day 18 ---

# (File automatically generated by aocTool, developed by B0lu, 2020.)

class Num():
	def __init__(self, n): self.n = n
	def __add__(self, other): return Num(self.n + other.n)
	def __sub__(self, other): return Num(self.n * other.n)

import re

print("Sum of results: " + str(sum(eval(op).n for op in re.sub(r"(\d)", r"Num(\1)", open("input.txt").read()).replace("*", "-").splitlines())))
assert sum(eval(op).n for op in re.sub(r"(\d)", r"Num(\1)", open("input.txt").read()).replace("*", "-").splitlines()) == 1408133923393
