# --- Advent of code 2020: Day 18 ---

# (File automatically generated by aocTool, developed by B0lu, 2020.)

import re

ops = open("input.txt").read()
ops = re.sub(r"(\d)", r"Num(\1)", ops)
ops = re.sub(r"\*", "x", ops)
ops = re.sub(r"\+", "*", ops)
ops = re.sub(r"x", "+", ops)
ops = ops.split("\n")[:-1]

class Num():
	def __init__(self, n):
		self.n = n

	def __add__(self, other):
		return Num(self.n * other.n)

	def __mul__(self, other):
		return Num(self.n + other.n)

r = []
for op in ops:
	#print(op)
	exec(f"r.append({op})")

int_r = [n.n for n in r]
print(sum(int_r))
assert sum(int_r) == 314455761823725
