# --- Advent of code 2020: Day 13 ---

# (File automatically generated by aocTool, developed by B0lu, 2020.)

t0, _l = open("input.txt").readlines()
t0 = int(t0)
lines = list(map(int, filter(lambda e: e != "x", _l.split(","))))
wait = {e - t0 % e: e for e in lines}

print(f"Bus ID * wait: {min(wait) * wait[min(wait)]}")
assert min(wait) * wait[min(wait)] == 3882
