# --- Advent of code 2020: Day 15 ---

# (File automatically generated by aocTool, developed by B0lu, 2020.)

starting = list(map(int, open("input.txt").read().split(",")))
last = {n: starting.index(n) + 1 for n in starting[:-1]}

current = starting[-1]
for i in range(len(starting), 2020):
	#print(i - 1, current, last0, last1)
	if current not in last:
		last[current] = i
		current = 0
	else:
		nxt = i - last[current]
		last[current] = i
		current = nxt

print(f"2020th number: {current}")
assert current == 1665
