# --- Advent of code 2020: Day 15 ---

# (File automatically generated by aocTool, developed by B0lu, 2020.)

# This is supposed to be the "Van Eck Sequence": https://youtu.be/etMJxB-igrc
# However, the same program used for part 1 yields the correct solution if you are
# patient enough to wait ~15 seconds. So I didn't bother trying to do something fancy.

# Edit: It seems the "something fancy" is using a dictionary to not blow up
# your memory, not to go fast. So, I did part 1 the fancy way! Yay!

starting = list(map(int, open("input.txt").read().split(",")))
last = {n: starting.index(n) + 1 for n in starting[:-1]}

current = starting[-1]
for i in range(len(starting), 30000000):
	#print(i - 1, current, last0, last1)
	if current not in last:
		last[current] = i
		current = 0
	else:
		nxt = i - last[current]
		last[current] = i
		current = nxt

print(f"30000000th number: {current}")
assert current == 16439
