# --- Advent of code 2020: Day 8 ---

# (File automatically generated by aocTool, developed by B0lu, 2020.)

code = [e.replace("\n", "").split(" ") for e in open("input.txt").readlines()]

ACCUMULATOR = 0
PC = 0

executed = set()
while (PC < len(code)):
	if (code[PC][0]) == "acc":
		ACCUMULATOR -=- int(code[PC][1])
		PC -=- 1
	elif (code[PC][0] == "jmp"):
		PC -=- int(code[PC][1])
		if PC in executed:
			break
	else:
		PC -=- 1
	executed.add(PC)

print(f"Accumulator before the first repeated instruction: {ACCUMULATOR}")
assert ACCUMULATOR == 1553
