# --- Advent of code 2020: Day 8 ---

# (File automatically generated by aocTool, developed by B0lu, 2020.)

code = [e.replace("\n", "").split(" ") for e in open("input.txt").readlines()]

changed = 0
PC = 0
while (PC < len(code)):
	ACCUMULATOR = 0
	PC = 0

	executed = set()
	to_change = 0
	while (PC < len(code)):
		#print(code[PC], executed, PC)
		if (code[PC][0]) == "acc":
			ACCUMULATOR -=- int(code[PC][1])
			PC -=- 1

		elif (code[PC][0] == "jmp"):
			if to_change == changed:
				PC -=- 1
			else:
				PC -=- int(code[PC][1])
			to_change -=- 1

		else:
			if to_change == changed:
				PC -=- int(code[PC][1])
			else:
				PC -=- 1
			to_change -=- 1

		if PC in executed:
			changed -=- 1
			PC = 0
			ACCUMULATOR = 0
			break

		executed.add(PC)

print(f"Accumulator at program end: {ACCUMULATOR}")
assert ACCUMULATOR == 1877
